// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyaTvzTSMxuzZTfPwmhKfb7rSUU-WpOrE',
    appId: '1:588301226396:web:3dc318a51a390e650cb859',
    messagingSenderId: '588301226396',
    projectId: 'gaiiachat',
    authDomain: 'gaiiachat.firebaseapp.com',
    storageBucket: 'gaiiachat.appspot.com',
    measurementId: 'G-EMZWQ5JJ61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCUJpJHSBASIUnwLy9YX4dAXVkZGvp2z4',
    appId: '1:588301226396:android:7013a06044b72cee0cb859',
    messagingSenderId: '588301226396',
    projectId: 'gaiiachat',
    storageBucket: 'gaiiachat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJ-fh6lQr6cfA56In0n3sDeBJpLwoHf00',
    appId: '1:588301226396:ios:5d58c14e34d021460cb859',
    messagingSenderId: '588301226396',
    projectId: 'gaiiachat',
    storageBucket: 'gaiiachat.appspot.com',
    iosClientId: '588301226396-8sl8ceqkojc10j6n764mem55k7dtr0r0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gaiiaChat',
  );
}
